spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/frenemy_db
spring.datasource.username=frenemy_user
spring.datasource.password=Frenemy123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG