### 1. Sprawdź aktualny stan postaci (przed questem)
GET http://localhost:8080/api/character/1

### 2. Zobacz dostępne questy (wybierz quest z dużą nagrodą XP)
GET http://localhost:8080/api/quests/random

### 3. Rozpocznij quest (userId=1, questId - wybierz z powyższego)
POST http://localhost:8080/api/quests/start?userId=1&questId=1

### 4. Ukończ quest i sprawdź czy postać awansowała
POST http://localhost:8080/api/quests/complete?userId=1

### 5. Sprawdź stan postaci po ukończeniu questa
# Powinieneś zobaczyć:
# - zwiększone experience
# - xpToNextLevel (ile brakuje do następnego poziomu)
# - xpProgressPercent (procent postępu)
# - jeśli awansowałeś: wyższy level i zwiększone statystyki
GET http://localhost:8080/api/characters/1