POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "ToJa",
  "password": "Tajne22Haslo123",
  "className": "Tropiciel",
  "characterName": "Rozpierdalacz",
  "raceName": "Nordowie"
}

